name: docker-pipeline-siva
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your regno
        run: echo "Hello World - 22it047"

      - name: Checkout repository
        uses: actions/checkout@v4 
        
      - name: Docker build
        run: docker build -t sivachidhambaram27/ml-model-22it047 .
        
      - name: Docker Image
        run: docker images
